# Package Overview
package_name: plant_disease_detection_model

# Data Files
training_data_file: datasets/new-plant-diseases-dataset

# Variables
# The variable we are attempting to predict (disease)
target: disease

pipeline_name: plant_disease_detection_model
pipeline_save_file: plant_disease_detection_model_output_v

# Set train/test split
test_size: 0.20

# Set the random seed
random_state: 42

# Set the batch size
batch_size: 128

color_mode: 'rgb'
class_mode: 'categorical'
size: 224
target_size: (size,size)
input_shape :  (224, 224, 3)
num_classes: 38

# Activation functions
dense_activation: 'relu'
output_activation: 'softmax'

learning_rate: 0.001
beta_1: 0.9
beta_2: 0.999
loss: "categorical_crossentropy"
metrics: ("accuracy",'precision','recall')
epochs:  10

# Alogrithm parameters
n_estimators: 100
max_depth: 10
