name: Retrain Model

on:
  workflow_dispatch:
    inputs:
      dataset_name:
        description: "Name of the dataset"
        required: true
      project_name:
        description: "Project name"
        required: true

jobs:
  retrain:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.6'
        cache: 'pip'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt

    - name: Train Model
      run: |
        python train_with_clearml.py --dataset ${{ inputs.dataset_name }} --project ${{ inputs.project_name }}
